apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mention-service
  name: user-mention-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-mention-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: user-mention-service
    spec:
      nodeName: tracing112
      containers:
        - command:
            - UserMentionService
          image: yg397/social-network-microservices:latest
          name: user-mention-service
          resources:
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: user-mention-service-claim0
      hostname: user-mention-service
      restartPolicy: Always
      volumes:
        - name: user-mention-service-claim0
          persistentVolumeClaim:
            claimName: user-mention-service-claim0
status: {}
