apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - command:
            - frontend
          env:
            - name: TLS
          image: hotel_reserv_frontend_single_node
          name: hotel-reserv-frontend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
